import {
  ABILITY_SLOTS,
  HERO_IDS,
  type AbilityDefinition,
  type AbilitySlot,
  type HeroId,
  type HeroKit,
} from './types'

export { ABILITY_SLOTS, HERO_IDS } from './types'
export type { AbilitySlot, HeroId, HeroKit } from './types'

function defineAbility(definition: AbilityDefinition): AbilityDefinition {
  return Object.freeze({
    ...definition,
    hitShape: Object.freeze({ ...definition.hitShape }),
    damage: definition.damage ? Object.freeze({ ...definition.damage }) : undefined,
    movement: definition.movement ? Object.freeze({ ...definition.movement }) : undefined,
    statuses: definition.statuses
      ? Object.freeze(definition.statuses.map((status) => Object.freeze({ ...status })))
      : undefined,
  })
}

function defineKit(
  definition: Omit<HeroKit, 'abilities'> & {
    readonly abilities: Readonly<Record<AbilitySlot, AbilityDefinition>>
  },
): HeroKit {
  const abilities = Object.fromEntries(
    ABILITY_SLOTS.map((slot) => [slot, defineAbility(definition.abilities[slot])]),
  ) as unknown as Readonly<Record<AbilitySlot, AbilityDefinition>>

  return Object.freeze({
    ...definition,
    stats: Object.freeze({ ...definition.stats }),
    abilities: Object.freeze(abilities),
  })
}

export const HERO_KITS: Readonly<Record<HeroId, HeroKit>> = Object.freeze({
  'luma-crivo': defineKit({
    id: 'luma-crivo',
    characterName: 'Luma Torres',
    codename: 'Crivo',
    gender: 'woman',
    role: 'controller',
    affinity: 'Crivo de Eratóstenes',
    description: 'Controladora de zona. Revela flancos, desacelera avanços e abre alvos para o time.',
    accent: '#63f5c5',
    stats: {
      maxHealth: 260,
      maxShield: 100,
      moveSpeed: 6.4,
      hitRadius: 0.42,
      ultimateGainPerDamage: 0.72,
    },
    abilities: {
      primary: {
        id: 'agulha-prima',
        slot: 'primary',
        name: 'Agulha Prima',
        spokenName: 'Agulha Prima!',
        description: 'Agulha estreita que causa dano extra em alvos revelados pela Malha.',
        mechanic: 'precision-shot',
        detonates: { bonus: 0.3, ultimateRefund: 6 },
        cooldownMs: 650,
        target: 'enemies',
        hitShape: { kind: 'ray', range: 42, radius: 0.08 },
        damage: { amount: 17 },
        maxTargets: 1,
      },
      signature: {
        id: 'malha-de-eratostenes',
        slot: 'signature',
        name: 'Malha de Eratóstenes',
        spokenName: 'Crivo de Eratóstenes!',
        description: 'Zona persistente de leitura: revela e reduz o avanço inimigo.',
        mechanic: 'sieve-field',
        cooldownMs: 9_500,
        target: 'enemies',
        hitShape: { kind: 'radius', center: 'aim', radius: 5, maxRange: 25 },
        damage: { amount: 10 },
        statuses: [
          { id: 'slowed', durationMs: 2_600, magnitude: 0.24, appliesTo: 'targets' },
          { id: 'revealed', durationMs: 5_000, magnitude: 1, appliesTo: 'targets' },
          { id: 'marked', durationMs: 5_000, magnitude: 0.14, appliesTo: 'targets' },
        ],
        maxTargets: 6,
      },
      mobility: {
        id: 'salto-residual',
        slot: 'mobility',
        name: 'Salto Residual',
        spokenName: 'Residuo primo!',
        description: 'Passo lateral seguro para trocar de ângulo sem abandonar a zona.',
        mechanic: 'residue-dash',
        cooldownMs: 6_000,
        target: 'self',
        hitShape: { kind: 'ray', range: 8, radius: 0 },
        movement: { kind: 'dash', distance: 8 },
      },
      ultimate: {
        id: 'dominio-do-crivo',
        slot: 'ultimate',
        name: 'Domínio do Crivo',
        spokenName: 'Domínio... do Crivo!',
        description: 'Domínio amplo que expõe a equipe rival e interrompe habilidades por uma janela curta.',
        mechanic: 'sieve-domain',
        cooldownMs: 1_000,
        target: 'enemies',
        hitShape: { kind: 'radius', center: 'caster', radius: 15 },
        damage: { amount: 48 },
        statuses: [
          { id: 'revealed', durationMs: 5_000, magnitude: 1, appliesTo: 'targets' },
          { id: 'silenced', durationMs: 1_400, magnitude: 1, appliesTo: 'targets' },
        ],
        maxTargets: 12,
        ultimateCost: 100,
      },
    },
  }),

  'raul-rsa': defineKit({
    id: 'raul-rsa',
    characterName: 'Raul Sato',
    codename: 'RSA',
    gender: 'man',
    role: 'tank',
    affinity: 'Módulo RSA p × q',
    description: 'Vanguarda de linha de frente. Absorve pressão, protege o ponto e pune fogo concentrado.',
    accent: '#ffc857',
    stats: {
      maxHealth: 325,
      maxShield: 175,
      moveSpeed: 5.15,
      hitRadius: 0.52,
      ultimateGainPerDamage: 0.58,
    },
    abilities: {
      primary: {
        id: 'canhao-semiprimo',
        slot: 'primary',
        name: 'Canhão Semiprimo',
        spokenName: 'Produto selado!',
        description: 'Cinco fatores que convergem no centro e se dispersam com distância e ângulo.',
        mechanic: 'scatter-shot',
        cooldownMs: 1_100,
        target: 'enemies',
        hitShape: { kind: 'cone', range: 15, halfAngleDegrees: 9 },
        damage: { amount: 6, instances: 5 },
        statuses: [
          { id: 'marked', durationMs: 3_200, magnitude: 0.1, appliesTo: 'targets' },
        ],
        maxTargets: 3,
      },
      signature: {
        id: 'produto-pq',
        slot: 'signature',
        name: 'Produto p × q',
        spokenName: 'Chave privada: p vezes q!',
        description: 'Reforça o escudo e reflete pressão enquanto Raul sustenta a linha.',
        mechanic: 'rsa-barrier',
        cooldownMs: 11_000,
        target: 'self',
        hitShape: { kind: 'radius', center: 'caster', radius: 0 },
        shieldGain: 120,
        statuses: [
          { id: 'reflecting', durationMs: 3_500, magnitude: 0.22, appliesTo: 'caster' },
        ],
      },
      mobility: {
        id: 'investida-modular',
        slot: 'mobility',
        name: 'Investida Modular',
        spokenName: 'Módulo em avanço!',
        description: 'Investida telegrafada que rompe a formação e cria espaço para aliados.',
        mechanic: 'modular-charge',
        detonates: { bonus: 0.34, ultimateRefund: 4, cooldownRefundMs: 1_800 },
        cooldownMs: 8_000,
        target: 'enemies',
        hitShape: { kind: 'ray', range: 7.5, radius: 0.9 },
        damage: { amount: 22 },
        movement: { kind: 'dash', distance: 7.5 },
        statuses: [
          { id: 'slowed', durationMs: 900, magnitude: 0.2, appliesTo: 'targets' },
        ],
        maxTargets: 3,
      },
      ultimate: {
        id: 'bastiao-rsa',
        slot: 'ultimate',
        name: 'Bastião RSA',
        spokenName: 'Bastião... RSA!',
        description: 'Bastião de equipe: restaura o módulo e transforma pressão em contra-ataque.',
        mechanic: 'rsa-bastion',
        cooldownMs: 1_000,
        target: 'enemies',
        hitShape: { kind: 'radius', center: 'caster', radius: 15 },
        damage: { amount: 28 },
        shieldGain: 175,
        statuses: [
          { id: 'reflecting', durationMs: 5_000, magnitude: 0.35, appliesTo: 'caster' },
        ],
        maxTargets: 12,
        ultimateCost: 100,
      },
    },
  }),

  'teo-gemeos': defineKit({
    id: 'teo-gemeos',
    characterName: 'Teo Arendt',
    codename: 'Gêmeos',
    gender: 'man',
    role: 'assault',
    affinity: 'Primos gêmeos',
    description: 'Assalto móvel. Encadeia pares de disparos, marca duelistas e fecha eliminações.',
    accent: '#ff5bd6',
    stats: {
      maxHealth: 280,
      maxShield: 80,
      moveSpeed: 7.45,
      hitRadius: 0.41,
      ultimateGainPerDamage: 0.68,
    },
    abilities: {
      primary: {
        id: 'rajada-11-13',
        slot: 'primary',
        name: 'Rajada 11–13',
        spokenName: 'Onze... treze!',
        description: 'Par de projéteis que converge e consome a marca para um acerto amplificado.',
        mechanic: 'paired-burst',
        // Combo payoff: 11 marks, 13 detonates.
        detonates: { bonus: 0.22, ultimateRefund: 5, cooldownRefundMs: 0 },
        cooldownMs: 680,
        target: 'enemies',
        hitShape: { kind: 'ray', range: 38, radius: 0.1 },
        damage: { amount: 9, instances: 2 },
        maxTargets: 1,
      },
      signature: {
        id: 'detonacao-gemea',
        slot: 'signature',
        name: 'Detonação Gêmea',
        spokenName: 'Convergência gêmea!',
        description: 'Duas frentes em cone marcam rivais para o próximo combo da equipe.',
        mechanic: 'twin-detonation',
        cooldownMs: 7_000,
        target: 'enemies',
        hitShape: { kind: 'cone', range: 23, halfAngleDegrees: 12 },
        damage: { amount: 18, instances: 2 },
        statuses: [
          { id: 'marked', durationMs: 3_600, magnitude: 0.12, appliesTo: 'targets' },
        ],
        maxTargets: 5,
      },
      mobility: {
        id: 'passo-17-19',
        slot: 'mobility',
        name: 'Passo 17–19',
        spokenName: 'Dezessete, dezenove!',
        description: 'Dash duplo para perseguir um alvo ou quebrar linha de visão.',
        mechanic: 'echo-step',
        cooldownMs: 4_500,
        target: 'self',
        hitShape: { kind: 'ray', range: 10.5, radius: 0 },
        movement: { kind: 'dash', distance: 10.5 },
      },
      ultimate: {
        id: 'conjectura-gemea',
        slot: 'ultimate',
        name: 'Conjectura Gêmea',
        spokenName: 'Conjectura... Gêmea!',
        description: 'Dois trilhos atravessam a frente; devastador quando a equipe alinha os rivais.',
        mechanic: 'twin-conjecture',
        cooldownMs: 1_000,
        target: 'enemies',
        hitShape: { kind: 'cone', range: 42, halfAngleDegrees: 24 },
        damage: { amount: 34, instances: 2 },
        statuses: [
          { id: 'marked', durationMs: 4_000, magnitude: 0.16, appliesTo: 'targets' },
        ],
        maxTargets: 12,
        ultimateCost: 100,
      },
    },
  }),

  'yara-diffie': defineKit({
    id: 'yara-diffie',
    characterName: 'Yara Okafor',
    codename: 'Diffie',
    gender: 'woman',
    role: 'infiltrator',
    affinity: 'Troca de chaves Diffie–Hellman',
    description: 'Flanqueadora de informação. Cria sinais falsos, some da mira e escolhe quando duelar.',
    accent: '#9a7cff',
    stats: {
      maxHealth: 250,
      maxShield: 90,
      moveSpeed: 7.05,
      hitRadius: 0.4,
      ultimateGainPerDamage: 0.76,
    },
    abilities: {
      primary: {
        id: 'pulso-discreto',
        slot: 'primary',
        name: 'Pulso Discreto',
        spokenName: 'Logaritmo discreto!',
        description: 'Pulso estreito que rompe o próprio manto para causar dano de emboscada.',
        mechanic: 'suppressed-shot',
        detonates: { bonus: 0.38, ultimateRefund: 7 },
        cooldownMs: 650,
        target: 'enemies',
        hitShape: { kind: 'ray', range: 40, radius: 0.07 },
        damage: { amount: 17 },
        maxTargets: 1,
      },
      signature: {
        id: 'chave-publica',
        slot: 'signature',
        name: 'Chave Pública',
        spokenName: 'Chave pública enviada!',
        description: 'Isca pública em área: denuncia e marca quem atravessa o sinal.',
        mechanic: 'public-key-decoy',
        cooldownMs: 8_000,
        target: 'enemies',
        hitShape: { kind: 'radius', center: 'aim', radius: 3.6, maxRange: 26 },
        damage: { amount: 10 },
        statuses: [
          { id: 'marked', durationMs: 4_000, magnitude: 0.16, appliesTo: 'targets' },
        ],
        maxTargets: 5,
      },
      mobility: {
        id: 'troca-de-chave',
        slot: 'mobility',
        name: 'Troca de Chave',
        spokenName: 'Segredo compartilhado!',
        description: 'Blink de infiltração que apaga sua silhueta por uma janela curta.',
        mechanic: 'key-exchange',
        cooldownMs: 6_500,
        target: 'self',
        hitShape: { kind: 'ray', range: 13, radius: 0 },
        movement: { kind: 'blink', distance: 13 },
        statuses: [
          { id: 'cloaked', durationMs: 2_600, magnitude: 1, appliesTo: 'caster' },
        ],
      },
      ultimate: {
        id: 'segredo-compartilhado',
        slot: 'ultimate',
        name: 'Segredo Compartilhado',
        spokenName: 'Segredo... Compartilhado!',
        description: 'Apaga a leitura local, silencia por instantes e dá a Yara uma rota de saída.',
        mechanic: 'shared-secret',
        cooldownMs: 1_000,
        target: 'enemies',
        hitShape: { kind: 'radius', center: 'caster', radius: 13 },
        damage: { amount: 48 },
        statuses: [
          { id: 'marked', durationMs: 4_000, magnitude: 0.18, appliesTo: 'targets' },
          { id: 'silenced', durationMs: 1_200, magnitude: 1, appliesTo: 'targets' },
          { id: 'cloaked', durationMs: 3_500, magnitude: 1, appliesTo: 'caster' },
        ],
        maxTargets: 12,
        ultimateCost: 100,
      },
    },
  }),
  'iris-mersenne': defineKit({
    id: 'iris-mersenne',
    characterName: 'Íris Mersenne',
    codename: 'LANÇA 2^p−1',
    gender: 'woman',
    role: 'infiltrator',
    affinity: 'Primos de Mersenne',
    description: 'Atiradora de longo alcance: marca à distância, arma armadilhas perfeitas e cobra tudo de uma vez.',
    accent: '#7dff8f',
    stats: {
      maxHealth: 250,
      maxShield: 90,
      moveSpeed: 6.1,
      hitRadius: 0.52,
      ultimateGainPerDamage: 0.62,
    },
    abilities: {
      primary: {
        id: 'lanca-de-mersenne',
        slot: 'primary',
        name: 'Lança de Mersenne',
        spokenName: 'Dois elevado a p, menos um!',
        description: 'Feixe longo e fino que perfura à distância e detona marcas em cheio.',
        mechanic: 'mersenne-lance',
        detonates: { bonus: 0.42, ultimateRefund: 8 },
        cooldownMs: 1_100,
        target: 'enemies',
        hitShape: { kind: 'ray', range: 34, radius: 0.42 },
        damage: { amount: 28 },
        maxTargets: 1,
      },
      signature: {
        id: 'armadilha-perfeita',
        slot: 'signature',
        name: 'Armadilha Perfeita',
        spokenName: 'Numero perfeito, soma fechada!',
        description: 'Campo de números perfeitos que prende, revela e marca quem pisar nele.',
        mechanic: 'perfect-trap',
        cooldownMs: 10_000,
        target: 'enemies',
        hitShape: { kind: 'radius', center: 'aim', radius: 5.5, maxRange: 26 },
        damage: { amount: 12 },
        statuses: [
          { id: 'slowed', durationMs: 3_000, magnitude: 0.34, appliesTo: 'targets' },
          { id: 'revealed', durationMs: 5_500, magnitude: 1, appliesTo: 'targets' },
          { id: 'marked', durationMs: 5_500, magnitude: 0.18, appliesTo: 'targets' },
        ],
        maxTargets: 5,
      },
      mobility: {
        id: 'salto-exponencial',
        slot: 'mobility',
        name: 'Salto Exponencial',
        spokenName: 'Expoente livre!',
        description: 'Recuo instantâneo para reabrir a distância que a lança exige.',
        mechanic: 'exponent-leap',
        cooldownMs: 7_500,
        target: 'self',
        hitShape: { kind: 'radius', center: 'caster', radius: 3 },
        movement: { kind: 'blink', distance: 9.5 },
        statuses: [
          { id: 'cloaked', durationMs: 1_400, magnitude: 1, appliesTo: 'caster' },
        ],
      },
      ultimate: {
        id: 'cascata-de-mersenne',
        slot: 'ultimate',
        name: 'Cascata de Mersenne',
        spokenName: 'A cascata nao para!',
        description: 'Cobra todas as marcas do campo de uma vez, em cascata.',
        mechanic: 'mersenne-cascade',
        detonates: { bonus: 0.75, ultimateRefund: 0 },
        cooldownMs: 1_000,
        target: 'enemies',
        hitShape: { kind: 'radius', center: 'caster', radius: 15 },
        damage: { amount: 42 },
        statuses: [
          { id: 'revealed', durationMs: 4_000, magnitude: 1, appliesTo: 'targets' },
        ],
        maxTargets: 12,
        ultimateCost: 100,
      },
    },
  }),
})

export const HERO_KIT_LIST: readonly HeroKit[] = Object.freeze(
  HERO_IDS.map((id) => HERO_KITS[id]),
)

export function isHeroId(value: string): value is HeroId {
  return HERO_IDS.includes(value as HeroId)
}

export function getHeroKit(id: HeroId | string): HeroKit {
  if (!isHeroId(id)) throw new RangeError(`Unknown Núcleo 257 hero: ${id}`)
  return HERO_KITS[id]
}
